services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ec_system
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    command: [
      "mysqld",
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_0900_ai_ci",
      "--default-authentication-plugin=mysql_native_password"
    ]
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql

  web:
    image: python:3.11
    working_dir: /app
    volumes:
      - ./backend:/app
    command: >
      bash -lc "
      pip install django djangorestframework mysqlclient &&
      if [ ! -f manage.py ]; then django-admin startproject config .; fi &&
      python manage.py runserver 0.0.0.0:8000
      "
    ports:
      - "8000:8000"
    depends_on:
      - db

  phpmyadmin:
    image: phpmyadmin:5-apache
    environment:
      PMA_HOST: db
      PMA_USER: app
      PMA_PASSWORD: app
    ports:
      - "5050:80"

volumes:
  mysqldata: